SRC=pmic_babbling.tex

all: pmic_babbling.pdf

pmic_babbling.pdf: pmic_babbling.tex
	pdflatex pmic_babbling.tex

clean:
	rm -rf pmic_babbling.pdf

clean_intermediate:
	rm -rf pmic_babbling.log
	rm -rf pmic_babbling.nav
	rm -rf pmic_babbling.out
	rm -rf pmic_babbling.snm
	rm -rf pmic_babbling.vrb
	rm -rf pmic_babbling.toc
	rm -rf pmic_babbling.aux

